#ifndef __TASK1853_CLIENT_CONTEXT_H__
#define __TASK1853_CLIENT_CONTEXT_H__

typedef enum
{
    TASK1853_TASK_STATUS_UNKNOWN = 0,
    TASK1853_TASK_STATUS_START_PENDING,
    TASK1853_TASK_STATUS_RUNNING,
    TASK1853_TASK_STATUS_STOP_PENDING,
}TASK1853_TASK_STATUS_E;

typedef struct
{
    INT32 hwnd;
    INT32 taskId;
    TASK1853_TASK_STATUS_E task_status;
}TZ1853_CLIENT_CONTEXT_S;


#endif
