#ifndef __SNAIL_ERRNO_H__
#define __SNAIL_ERRNO_H__
#include "xrrno.h"

typedef enum
{
    SNAIL_ERRNO_SUCCESS     = ERRNO_SUCCESS,
    SNAIL_ERRNO_FAILED      = ERRNO_FAILED,
    SNAIL_ERRNO_INVALID     = ERRNO_INVALID,
    SNAIL_ERRNO_NOMEM       = ERRNO_NOMEM,
    SNAIL_ERRNO_NOSPACE     = ERRNO_NOSPACE,
    SNAIL_ERRNO_NETWORK     = ERRNO_NETWORK,
    SNAIL_ERRNO_NOT_EXIST   = ERRNO_NOT_EXIST,
    SNAIL_ERRNO_EXIST       = ERRNO_EXIST,
    SNAIL_ERRNO_EXIT        = ERRNO_EXIT,
    SNAIL_ERRNO_EXCEPTION   = ERRNO_EXCEPTION,
    SNAIL_ERRNO_AGAIN       = ERRNO_AGAIN,
    SNAIL_ERRNO_INGORE      = ERRNO_IGNORE,
    SNAIL_ERRNO_REALIVE     = ERRNO_REALIVE,
    SNAIL_ERRNO_BLOCKED     = ERRNO_BLOCKED,
    SNAIL_ERRNO_OFFLINE     = ERRNO_OFFLINE,
    SNAIL_ERRNO_NOMORE      = ERRNO_NOMORE,
}SNAIL_ERRNO_E;


#endif